model_name: 'deepseek-coder-33b-base-config'
model_path: ["/data/models/code_models/deepseek/deepseek-coder-33b-base/"]
type: ["CG", "CM", "CR", "CUF", "CUR"]
batch_size: 1
output_path: "deepseek-coder-33b-base"
max_memory: '{5:"80GIB", 6:"80GIB"}'

# top_k: [10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50]
# top_p: [0.75, 0.76, 0.77, 0.78, 0.79, 0.80, 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.90, 0.91, 0.92, 0.93, 0.94, 0.95]
# max_new_tokens: [512]
top_k: [50]
top_p: [0.95]
max_new_tokens: [256, 1024, 2048]
